namespace BookingApp.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Ispravkamodela : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Comments", "User_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.RoomReservations", "User_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.Accommodations", "AppUser_Id", "dbo.AppUsers");
            DropForeignKey("dbo.Comments", "Accomodation_Id", "dbo.Accommodations");
            DropForeignKey("dbo.Accommodations", "Owner_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.Accommodations", "Place_Id", "dbo.Places");
            DropForeignKey("dbo.Rooms", "Accomodation_Id", "dbo.Accommodations");
            DropForeignKey("dbo.Accommodations", "AccomodationType_Id", "dbo.AccommodationTypes");
            DropForeignKey("dbo.RoomReservations", "Room_Id", "dbo.Rooms");
            DropForeignKey("dbo.Places", "Region_Id", "dbo.Regions");
            DropForeignKey("dbo.Regions", "Country_Id", "dbo.Countries");
            DropForeignKey("dbo.Comments", "AppUser_Id", "dbo.AppUsers");
            DropForeignKey("dbo.RoomReservations", "AppUser_Id", "dbo.AppUsers");
            DropIndex("dbo.Accommodations", new[] { "AccomodationType_Id" });
            DropIndex("dbo.Accommodations", new[] { "Owner_Id" });
            DropIndex("dbo.Accommodations", new[] { "Place_Id" });
            DropIndex("dbo.Accommodations", new[] { "AppUser_Id" });
            DropIndex("dbo.Comments", new[] { "Accomodation_Id" });
            DropIndex("dbo.Comments", new[] { "User_Id" });
            DropIndex("dbo.Comments", new[] { "AppUser_Id" });
            DropIndex("dbo.RoomReservations", new[] { "Room_Id" });
            DropIndex("dbo.RoomReservations", new[] { "User_Id" });
            DropIndex("dbo.RoomReservations", new[] { "AppUser_Id" });
            DropIndex("dbo.Rooms", new[] { "Accomodation_Id" });
            DropIndex("dbo.Places", new[] { "Region_Id" });
            DropIndex("dbo.Regions", new[] { "Country_Id" });
            RenameColumn(table: "dbo.Comments", name: "Accomodation_Id", newName: "AccommodationId");
            RenameColumn(table: "dbo.Accommodations", name: "Owner_Id", newName: "OwnerId");
            RenameColumn(table: "dbo.Accommodations", name: "Place_Id", newName: "PlaceId");
            RenameColumn(table: "dbo.Rooms", name: "Accomodation_Id", newName: "AccomodationId");
            RenameColumn(table: "dbo.Accommodations", name: "AccomodationType_Id", newName: "AccommodationTypeId");
            RenameColumn(table: "dbo.RoomReservations", name: "Room_Id", newName: "RoomId");
            RenameColumn(table: "dbo.Places", name: "Region_Id", newName: "RegionId");
            RenameColumn(table: "dbo.Regions", name: "Country_Id", newName: "CountryId");
            RenameColumn(table: "dbo.Comments", name: "AppUser_Id", newName: "AppUserId");
            RenameColumn(table: "dbo.RoomReservations", name: "AppUser_Id", newName: "AppUserId");
            DropPrimaryKey("dbo.Comments");
            AddColumn("dbo.Accommodations", "AverageGrade", c => c.Int(nullable: false));
            AddColumn("dbo.AspNetUsers", "AppUserId", c => c.Int());
            AddColumn("dbo.RoomReservations", "EndData", c => c.DateTime(nullable: false));
            AddColumn("dbo.AppUsers", "Name", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.AppUsers", "LastName", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Accommodations", "Name", c => c.String(nullable: false, maxLength: 256));
            AlterColumn("dbo.Accommodations", "Description", c => c.String(maxLength: 1024));
            AlterColumn("dbo.Accommodations", "Address", c => c.String(maxLength: 256));
            AlterColumn("dbo.Accommodations", "AccommodationTypeId", c => c.Int(nullable: false));
            AlterColumn("dbo.Accommodations", "OwnerId", c => c.Int(nullable: false));
            AlterColumn("dbo.Accommodations", "PlaceId", c => c.Int(nullable: false));
            AlterColumn("dbo.AccommodationTypes", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Comments", "Grade", c => c.Double(nullable: false));
            AlterColumn("dbo.Comments", "AccommodationId", c => c.Int(nullable: false));
            AlterColumn("dbo.Comments", "AppUserId", c => c.Int(nullable: false));
            AlterColumn("dbo.RoomReservations", "RoomId", c => c.Int(nullable: false));
            AlterColumn("dbo.RoomReservations", "AppUserId", c => c.Int(nullable: false));
            AlterColumn("dbo.Rooms", "Description", c => c.String(maxLength: 1024));
            AlterColumn("dbo.Rooms", "AccomodationId", c => c.Int(nullable: false));
            AlterColumn("dbo.Places", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Places", "RegionId", c => c.Int(nullable: false));
            AlterColumn("dbo.Regions", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Regions", "CountryId", c => c.Int(nullable: false));
            AlterColumn("dbo.Countries", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.Countries", "Code", c => c.String(nullable: false, maxLength: 10));
            AddPrimaryKey("dbo.Comments", new[] { "AppUserId", "AccommodationId" });
            CreateIndex("dbo.Accommodations", "AccommodationTypeId");
            CreateIndex("dbo.Accommodations", "PlaceId");
            CreateIndex("dbo.Accommodations", "OwnerId");
            CreateIndex("dbo.AccommodationTypes", "Name", unique: true);
            CreateIndex("dbo.Comments", "AppUserId");
            CreateIndex("dbo.Comments", "AccommodationId");
            CreateIndex("dbo.RoomReservations", "AppUserId");
            CreateIndex("dbo.RoomReservations", "RoomId");
            CreateIndex("dbo.Rooms", "AccomodationId");
            CreateIndex("dbo.Places", "RegionId");
            CreateIndex("dbo.Regions", "CountryId");
            CreateIndex("dbo.AspNetUsers", "AppUserId");
            AddForeignKey("dbo.AspNetUsers", "AppUserId", "dbo.AppUsers", "Id");
            AddForeignKey("dbo.Comments", "AccommodationId", "dbo.Accommodations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Accommodations", "OwnerId", "dbo.AppUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Accommodations", "PlaceId", "dbo.Places", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Rooms", "AccomodationId", "dbo.Accommodations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Accommodations", "AccommodationTypeId", "dbo.AccommodationTypes", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RoomReservations", "RoomId", "dbo.Rooms", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Places", "RegionId", "dbo.Regions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Regions", "CountryId", "dbo.Countries", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Comments", "AppUserId", "dbo.AppUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RoomReservations", "AppUserId", "dbo.AppUsers", "Id", cascadeDelete: true);
            DropColumn("dbo.Accommodations", "AvrageGrade");
            DropColumn("dbo.Accommodations", "AppUser_Id");
            DropColumn("dbo.Comments", "Id");
            DropColumn("dbo.Comments", "User_Id");
            DropColumn("dbo.RoomReservations", "EndDate");
            DropColumn("dbo.RoomReservations", "User_Id");
            DropColumn("dbo.AppUsers", "FullName");
            DropColumn("dbo.AppUsers", "Username");
            DropColumn("dbo.AppUsers", "Email");
            DropColumn("dbo.AppUsers", "Password");
        }
        
        public override void Down()
        {
            AddColumn("dbo.AppUsers", "Password", c => c.String());
            AddColumn("dbo.AppUsers", "Email", c => c.String());
            AddColumn("dbo.AppUsers", "Username", c => c.String());
            AddColumn("dbo.AppUsers", "FullName", c => c.String());
            AddColumn("dbo.RoomReservations", "User_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.RoomReservations", "EndDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Comments", "User_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.Comments", "Id", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Accommodations", "AppUser_Id", c => c.Int());
            AddColumn("dbo.Accommodations", "AvrageGrade", c => c.Double(nullable: false));
            DropForeignKey("dbo.RoomReservations", "AppUserId", "dbo.AppUsers");
            DropForeignKey("dbo.Comments", "AppUserId", "dbo.AppUsers");
            DropForeignKey("dbo.Regions", "CountryId", "dbo.Countries");
            DropForeignKey("dbo.Places", "RegionId", "dbo.Regions");
            DropForeignKey("dbo.RoomReservations", "RoomId", "dbo.Rooms");
            DropForeignKey("dbo.Accommodations", "AccommodationTypeId", "dbo.AccommodationTypes");
            DropForeignKey("dbo.Rooms", "AccomodationId", "dbo.Accommodations");
            DropForeignKey("dbo.Accommodations", "PlaceId", "dbo.Places");
            DropForeignKey("dbo.Accommodations", "OwnerId", "dbo.AppUsers");
            DropForeignKey("dbo.Comments", "AccommodationId", "dbo.Accommodations");
            DropForeignKey("dbo.AspNetUsers", "AppUserId", "dbo.AppUsers");
            DropIndex("dbo.AspNetUsers", new[] { "AppUserId" });
            DropIndex("dbo.Regions", new[] { "CountryId" });
            DropIndex("dbo.Places", new[] { "RegionId" });
            DropIndex("dbo.Rooms", new[] { "AccomodationId" });
            DropIndex("dbo.RoomReservations", new[] { "RoomId" });
            DropIndex("dbo.RoomReservations", new[] { "AppUserId" });
            DropIndex("dbo.Comments", new[] { "AccommodationId" });
            DropIndex("dbo.Comments", new[] { "AppUserId" });
            DropIndex("dbo.AccommodationTypes", new[] { "Name" });
            DropIndex("dbo.Accommodations", new[] { "OwnerId" });
            DropIndex("dbo.Accommodations", new[] { "PlaceId" });
            DropIndex("dbo.Accommodations", new[] { "AccommodationTypeId" });
            DropPrimaryKey("dbo.Comments");
            AlterColumn("dbo.Countries", "Code", c => c.String());
            AlterColumn("dbo.Countries", "Name", c => c.String());
            AlterColumn("dbo.Regions", "CountryId", c => c.Int());
            AlterColumn("dbo.Regions", "Name", c => c.String());
            AlterColumn("dbo.Places", "RegionId", c => c.Int());
            AlterColumn("dbo.Places", "Name", c => c.String());
            AlterColumn("dbo.Rooms", "AccomodationId", c => c.Int());
            AlterColumn("dbo.Rooms", "Description", c => c.String());
            AlterColumn("dbo.RoomReservations", "AppUserId", c => c.Int());
            AlterColumn("dbo.RoomReservations", "RoomId", c => c.Int());
            AlterColumn("dbo.Comments", "AppUserId", c => c.Int());
            AlterColumn("dbo.Comments", "AccommodationId", c => c.Int());
            AlterColumn("dbo.Comments", "Grade", c => c.Int(nullable: false));
            AlterColumn("dbo.AccommodationTypes", "Name", c => c.String());
            AlterColumn("dbo.Accommodations", "PlaceId", c => c.Int());
            AlterColumn("dbo.Accommodations", "OwnerId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Accommodations", "AccommodationTypeId", c => c.Int());
            AlterColumn("dbo.Accommodations", "Address", c => c.String());
            AlterColumn("dbo.Accommodations", "Description", c => c.String());
            AlterColumn("dbo.Accommodations", "Name", c => c.String());
            DropColumn("dbo.AppUsers", "LastName");
            DropColumn("dbo.AppUsers", "Name");
            DropColumn("dbo.RoomReservations", "EndData");
            DropColumn("dbo.AspNetUsers", "AppUserId");
            DropColumn("dbo.Accommodations", "AverageGrade");
            AddPrimaryKey("dbo.Comments", "Id");
            RenameColumn(table: "dbo.RoomReservations", name: "AppUserId", newName: "AppUser_Id");
            RenameColumn(table: "dbo.Comments", name: "AppUserId", newName: "AppUser_Id");
            RenameColumn(table: "dbo.Regions", name: "CountryId", newName: "Country_Id");
            RenameColumn(table: "dbo.Places", name: "RegionId", newName: "Region_Id");
            RenameColumn(table: "dbo.RoomReservations", name: "RoomId", newName: "Room_Id");
            RenameColumn(table: "dbo.Accommodations", name: "AccommodationTypeId", newName: "AccomodationType_Id");
            RenameColumn(table: "dbo.Rooms", name: "AccomodationId", newName: "Accomodation_Id");
            RenameColumn(table: "dbo.Accommodations", name: "PlaceId", newName: "Place_Id");
            RenameColumn(table: "dbo.Accommodations", name: "OwnerId", newName: "Owner_Id");
            RenameColumn(table: "dbo.Comments", name: "AccommodationId", newName: "Accomodation_Id");
            CreateIndex("dbo.Regions", "Country_Id");
            CreateIndex("dbo.Places", "Region_Id");
            CreateIndex("dbo.Rooms", "Accomodation_Id");
            CreateIndex("dbo.RoomReservations", "AppUser_Id");
            CreateIndex("dbo.RoomReservations", "User_Id");
            CreateIndex("dbo.RoomReservations", "Room_Id");
            CreateIndex("dbo.Comments", "AppUser_Id");
            CreateIndex("dbo.Comments", "User_Id");
            CreateIndex("dbo.Comments", "Accomodation_Id");
            CreateIndex("dbo.Accommodations", "AppUser_Id");
            CreateIndex("dbo.Accommodations", "Place_Id");
            CreateIndex("dbo.Accommodations", "Owner_Id");
            CreateIndex("dbo.Accommodations", "AccomodationType_Id");
            AddForeignKey("dbo.RoomReservations", "AppUser_Id", "dbo.AppUsers", "Id");
            AddForeignKey("dbo.Comments", "AppUser_Id", "dbo.AppUsers", "Id");
            AddForeignKey("dbo.Regions", "Country_Id", "dbo.Countries", "Id");
            AddForeignKey("dbo.Places", "Region_Id", "dbo.Regions", "Id");
            AddForeignKey("dbo.RoomReservations", "Room_Id", "dbo.Rooms", "Id");
            AddForeignKey("dbo.Accommodations", "AccomodationType_Id", "dbo.AccommodationTypes", "Id");
            AddForeignKey("dbo.Rooms", "Accomodation_Id", "dbo.Accommodations", "Id");
            AddForeignKey("dbo.Accommodations", "Place_Id", "dbo.Places", "Id");
            AddForeignKey("dbo.Accommodations", "Owner_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Comments", "Accomodation_Id", "dbo.Accommodations", "Id");
            AddForeignKey("dbo.Accommodations", "AppUser_Id", "dbo.AppUsers", "Id");
            AddForeignKey("dbo.RoomReservations", "User_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Comments", "User_Id", "dbo.AspNetUsers", "Id");
        }
    }
}
